#!/bin/sh

echo "PReDoc 1.x (development release)"
echo "Written and Copyright (C) 1998 by Mark-André Hopf"
echo "PReDoc is free software, covered by the GNU General Public License, and you are welcome to change it and/or distribute copies of it under certain conditions."
echo 'Open "Help|Copyright" to see the conditions.'
echo ""
echo "Starting java..."

cd class
exec java predoc

jdk=/opt/jdk1.1.3
jdklib=${jdk}/lib/i586/green_threads
oldlib="/usr/X11R6/lib-3.3.2"

#export LD_PRELOAD="${oldlib}/libX11.so ${oldlib}/libXext.so \
#${oldlib}/libSM.so ${oldlib}/libICE.so ${oldlib}/libXt.so"

export LD_AOUT_LIBRARY_PATH=${oldlib}

export THREADS_TYPE=green_threads
export JAVA_HOME=${jdk}
export CLASSPATH=${jdk}/lib
export LD_LIBRARY_PATH=${oldlib}:${jdklib}
exec ${jdk}/bin/i586/green_threads/java
